#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["Api_Endpoint/Api_Endpoint.csproj", "Api_Endpoint/"]
COPY ["Application/Application.csproj", "Application/"]
COPY ["Domain/Domain.csproj", "Domain/"]
RUN dotnet restore "Api_Endpoint/Api_Endpoint.csproj"
COPY . .
WORKDIR "/src/Api_Endpoint"
RUN dotnet build "Api_Endpoint.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Api_Endpoint.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Api_Endpoint.dll"]